"""
geoview_pyside6.build_harness.pyinstaller_preset
===================================================
PyInstaller ``.spec`` file factory tuned for GeoView desktop apps.

Every GeoView app runs on PySide6 + pyqtgraph + matplotlib + openpyxl and
wants:

 - **onedir** build (NOT onefile) — faster startup, smaller RAM, and Windows
   antivirus is friendlier when it can scan a real directory.
 - **windowed** (no console) — we ship GUIs.
 - **Pretendard fonts bundled** via ``add_data`` under the relative path
   ``geoview_pyside6/fonts``.
 - **Qt plugins** auto-discovered by PyInstaller's hook — no manual copy.
 - **Hidden imports** for libraries PyInstaller's static analysis misses
   (e.g. pyqtgraph submodules, matplotlib backends, reportlab renderers).
 - **VersionInfo** from :mod:`version_stamp` so the EXE carries its SHA
   in the Windows resource section.

The factory generates a ``.spec`` **text** rather than a Python object
because PyInstaller consumes .spec files literally. Callers can either
:func:`write_spec` to disk or inspect the returned string directly.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Sequence

from geoview_pyside6.io_safe import atomic_write_text

__all__ = [
    "PyInstallerConfig",
    "DEFAULT_HIDDEN_IMPORTS",
    "DEFAULT_DATAS",
    "make_spec_text",
    "write_spec",
]


# Hidden imports PyInstaller's static analysis tends to miss. Apps can
# extend this via PyInstallerConfig.extra_hidden_imports rather than
# mutating the shared default.
DEFAULT_HIDDEN_IMPORTS: tuple[str, ...] = (
    "pyqtgraph.graphicsItems",
    "pyqtgraph.exporters",
    "pyqtgraph.exporters.ImageExporter",
    "pyqtgraph.exporters.SVGExporter",
    "matplotlib.backends.backend_pdf",
    "matplotlib.backends.backend_svg",
    "matplotlib.backends.backend_agg",
    "openpyxl",
    "openpyxl.styles",
    "docx",
    "reportlab.pdfbase._fontdata_enc_winansi",
    "reportlab.pdfbase._fontdata_enc_macroman",
    "reportlab.pdfbase._fontdata_enc_standard",
)


# Shared data files every GeoView app needs — paths are relative to the
# _shared root so PyInstaller resolves them at build time.
DEFAULT_DATAS: tuple[tuple[str, str], ...] = (
    # (source, dest_in_bundle)
    ("_shared/geoview_pyside6/fonts", "geoview_pyside6/fonts"),
)


@dataclass
class PyInstallerConfig:
    """Inputs for :func:`make_spec_text`."""

    app_name: str
    entry_script: Path | str
    icon_path: Path | str | None = None
    version_file: Path | str | None = None
    extra_datas: Sequence[tuple[str, str]] = field(default_factory=tuple)
    extra_hidden_imports: Sequence[str] = field(default_factory=tuple)
    console: bool = False
    onefile: bool = False
    workpath: str = "build"
    distpath: str = "dist"

    def __post_init__(self) -> None:
        if not self.app_name:
            raise ValueError("PyInstallerConfig.app_name must not be empty")
        if any(ch in self.app_name for ch in '<>:"|?*\\/'):
            raise ValueError(
                f"PyInstallerConfig.app_name contains reserved char: "
                f"{self.app_name!r}"
            )


_SPEC_TEMPLATE = '''\
# -*- mode: python ; coding: utf-8 -*-
#
# Auto-generated PyInstaller spec for {app_name!r}
# Regenerated by geoview_pyside6.build_harness.pyinstaller_preset.make_spec_text
# Do not edit by hand — regenerate if the config changes.

block_cipher = None

a = Analysis(
    [{entry_script_literal}],
    pathex=[],
    binaries=[],
    datas={datas_literal},
    hiddenimports={hidden_literal},
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    {exe_body}
    name={app_name!r},
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console={console!r},
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,{icon_line}{version_line}
)
{coll_block}
'''


def _literal(value: object) -> str:
    """Render a Python literal that is safe to paste into the spec text."""
    return repr(value)


def make_spec_text(config: PyInstallerConfig) -> str:
    """
    Build a PyInstaller ``.spec`` file body from ``config``.

    Merges :data:`DEFAULT_DATAS` / :data:`DEFAULT_HIDDEN_IMPORTS` with
    the config's extras, injects the icon / VersionInfo lines when
    provided, and switches between the onedir ``COLLECT`` block and
    the onefile single-EXE form.
    """
    datas = list(DEFAULT_DATAS) + list(config.extra_datas)
    hidden = list(DEFAULT_HIDDEN_IMPORTS) + list(config.extra_hidden_imports)

    # Deduplicate while preserving order
    seen: set[tuple[str, str]] = set()
    unique_datas: list[tuple[str, str]] = []
    for entry in datas:
        if entry not in seen:
            seen.add(entry)
            unique_datas.append(entry)

    seen_hidden: set[str] = set()
    unique_hidden: list[str] = []
    for h in hidden:
        if h not in seen_hidden:
            seen_hidden.add(h)
            unique_hidden.append(h)

    icon_line = ""
    if config.icon_path:
        icon_line = f"\n    icon={str(config.icon_path)!r},"

    version_line = ""
    if config.version_file:
        version_line = f"\n    version={str(config.version_file)!r},"

    if config.onefile:
        exe_body = (
            "a.binaries,\n"
            "    a.zipfiles,\n"
            "    a.datas,\n"
            "    [],"
        )
        coll_block = ""
    else:
        exe_body = "[],\n    exclude_binaries=True,"
        coll_block = (
            "\ncoll = COLLECT(\n"
            "    exe,\n"
            "    a.binaries,\n"
            "    a.zipfiles,\n"
            "    a.datas,\n"
            "    strip=False,\n"
            "    upx=True,\n"
            "    upx_exclude=[],\n"
            f"    name={config.app_name!r},\n"
            ")\n"
        )

    return _SPEC_TEMPLATE.format(
        app_name=config.app_name,
        entry_script_literal=_literal(str(config.entry_script)),
        datas_literal=_literal(unique_datas),
        hidden_literal=_literal(unique_hidden),
        exe_body=exe_body,
        console=config.console,
        icon_line=icon_line,
        version_line=version_line,
        coll_block=coll_block,
    )


def write_spec(config: PyInstallerConfig, out_path: Path | str) -> Path:
    """Atomically write the generated spec to ``out_path``."""
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    atomic_write_text(out, make_spec_text(config), encoding="utf-8")
    return out
